# -*- mode: ruby -*-
# vi: set ft=ruby :

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  # All Vagrant configuration is done here. The most common configuration
  # options are documented and commented below. For a complete reference,
  # please see the online documentation at vagrantup.com.

  # Every Vagrant virtual environment requires a box to build off of.
  config.vm.box = "ubuntu/trusty64"
  config.vm.network "private_network", ip: "192.168.60.10"

  # horizon
  #config.vm.network :forwarded_port, host: 8000, guest: 80, auto_correct: true

  # keystone
  #config.vm.network :forwarded_port, host: 5000, guest: 5000, auto_correct: true
  #config.vm.network :forwarded_port, host: 35357, guest: 35357, auto_correct: true

  config.vm.provider :virtualbox do |vb|
    vb.customize ["modifyvm", :id, "--memory", "8192"]
    vb.customize ["modifyvm", :id, "--cpus", "4"]
  end

  config.vm.provision :ansible do |ansible|
        ansible.playbook = "../../ansible/local-vagrant-vm.yml"
        ansible.verbose = "v"
  end

end
